const constants = {
  SORT_COLORS: 'SORT_COLORS',
  ADD_COLOR: 'ADD_COLOR',
  RATE_COLOR: 'RATE_COLOR',
  REMOVE_COLOR: 'REMOVE_COLOR',
  SORT_BY_DATE: 'SORT_BY_DATE',
  SORT_BY_TITLE: 'SORT_BY_TITLE',
  SORT_BY_RATING: 'SORT_BY_RATING',
};

export default constants;
