const constants = {
  SORT_COLORS: 'SORT_COLORS',
  ADD_COLOR: 'ADD_COLOR',
  RATE_COLOR: 'RATE_COLOR',
  REMOVE_COLOR: 'REMOVE_COLOR',
  SORTED_BY_DATE: 'SORTED_BY_DATE',
  SORTED_BY_TITLE: 'SORTED_BY_TITLE',
};

export default constants;
